config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  post    :login_or_register, to: 'sessions#create'
  delete  :logout, to: 'sessions#destroy'

  resources :movies, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  validates :url, presence: :true

  before_create :set_url

  protected

  def set_url
    self.url = url.gsub('watch?v=', 'embed/')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :movies, class_name: 'Movie', foreign_key: :author_id

  validates :username, presence: true, length: { maximum: 100 }, uniqueness: true
  validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  private

  def require_authenticate!
    unless logged_in?
      flash[:notice] = 'Require login or register'

      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :require_authenticate!

  def new
    @movie = Movie.new
  end

  def create
    @movie = current_user.movies.build(movie_params)

    if @movie.save
      flash[:success] = 'Share successfully'

      redirect_to root_path
    else
      render :new
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_initialize_by(username: param_username)

    if @user.new_record?
      @user.password = param_password
      @user.save
      flash[:success] = 'Register successfully'
      session[:user_id] = @user.id
    else
      if @user.authenticate(param_password)
        flash[:success] = 'Login successfully'
        session[:user_id] = @user.id
      else
        flash[:error] = 'Login unsuccessfully'
      end
    end

    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Logout successfully'

    redirect_to root_path
  end

  private

  def param_username
    params.require(:username)
  end

  def param_password
    params.require(:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-home fa-2x"></i>
    <span class="h3">Funny Movie</span>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>

    <% if logged_in? %>
      <div class="navbar-text mr-4">
        Welcome
        <span class="font-weight-bold"><%= current_user.username %></span>
      </div>

      <%= link_to 'Share a movie', new_movie_path, class: 'btn btn-outline-success my-2 my-sm-0 mr-4' %>
      <%= link_to 'Logout', logout_path, class: 'btn btn-outline-success my-2 my-sm-0', method: :delete, data: { confirm: 'Are you sure?' } %>
    <% else %>
      <%= form_with url: login_or_register_path, local: true, html: { class: 'form-inline my-2 my-lg-0' } do %>
        <%= text_field_tag :username, nil, class: 'form-control mr-sm-2', placeholder: 'username' %>
        <%= password_field_tag :password, nil, class: 'form-control mr-sm-2', placeholder: 'password' %><br>
        <%= submit_tag 'Login / Register', class: 'btn btn-outline-success my-2 my-sm-0' %>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-4">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="<%= movie.url %>" allowfullscreen></iframe>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <div class="container py-5">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/new.html.erb
<%= form_with model: @movie, locale: true do |f| %>
  <div class="form-group row">
    <%= f.label :url, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 offset-sm-2">
      <%= f.submit 'Share', class: 'btn btn-outline-success' %>
    </div>
  </div>
<% end %>